# Generated by Django 4.2.5 on 2023-10-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_youTube',
            new_name='social_youtube',
        ),
    ]
