# Generated by Django 4.2.5 on 2023-11-16 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytorrent', '0003_alter_home_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={},
        ),
        migrations.RemoveField(
            model_name='home',
            name='cat',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
