# Generated by Django 4.2.5 on 2023-10-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_projects_options_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ['-vote_ratio', '-vote_total', 'title']},
        ),
        migrations.AlterField(
            model_name='review',
            name='value',
            field=models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=200),
        ),
    ]
